metadata:
  name: "guestbook"
apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
asset_id: "667586565356"
spec:
  template:
    metadata:
      name: "{{cluster.name}}-guestbook"
    spec:
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "guestbook"
      project: "default"
      source:
        repoURL: "https://github.com/abhi-harness-cxe/applicationset.git"
        path: "examples/git-generator-files-discovery/apps/guestbook"
        targetRevision: "HEAD"
  generators:
  - git:
      repoURL: "https://github.com/abhi-harness-cxe/applicationset.git"
      files:
      - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
      revision: "HEAD"
